package dev.storyblock.validator;

public enum ValidationCode {
    BLOCK_TOO_LONG,
    INVALID_SENTENCE_COUNT,
    MULTIPLE_DIRECT_SPEAKERS,
    SPEAKER_NOT_PRESENT,
    META_EVIDENCE_REQUIRED,
    PRESENCE_EVENT_REQUIRED,
    EVIDENCE_SPAN_STALE,
    INVALID_BLOCK_ADJACENCY,
    REVISION_CONFLICT,
    UNKNOWN_META_VALUE_INVENTED
}
