module.exports=async({page,base,id,selected,click,shot,close,assert})=>{
  await page.goto(`${base}/?ui=v2#${id}`);await page.waitForSelector('#reader-title');
  assert.equal(await page.$eval('#reader-title',e=>e.textContent),selected.novel.title);
  await page.waitForFunction(()=>[...document.querySelectorAll('.story-image img')].every(e=>!e.hidden&&e.naturalWidth>0));
  assert.equal(await page.$$eval('.story-image img',e=>e.length),2);await shot('desktop-reader');
  await click('[data-chapter="1"]');
  assert.equal(await page.$eval('#chapter-heading',e=>e.textContent),selected.revision.chapters[1].title);
  await click('[data-lang="zh-Hant"]');
  assert.equal(await page.$eval('html',e=>e.lang),'zh-Hant');
  const content=await page.$$eval('.sb-block-text',es=>es.map(e=>e.textContent));
  await click('[data-lang="zh-Hans"]');assert.deepEqual(await page.$$eval('.sb-block-text',es=>es.map(e=>e.textContent)),content);
  await page.reload();await page.waitForSelector('#chapter-heading');
  assert.equal(await page.$eval('#chapter-heading',e=>e.textContent),selected.revision.chapters[1].title);
  await click('[data-lang=en]');await click('.sb-reader-actions [data-action=appearance]');
  await click('[data-key=size][data-value="28"]');
  assert.equal(await page.evaluate(()=>document.activeElement.dataset.value),'28','Preference button retains keyboard focus');
  await click('#block-mode');await close();await click('.sb-inspect');
  assert.match(await page.$eval('.sb-block-info',e=>e.textContent),/Recorded block metadata/);
  await close();await click('.sb-reader-actions [data-action=appearance]');
  await click('#block-mode');await click('[data-key=size][data-value="20"]');await close();
  await click('[data-chapter="0"]');
  await click('.sb-reader-bar [data-action=library]');await page.evaluate(()=>history.back());
  await page.waitForFunction(id=>location.hash==='#'+id&&!document.querySelector('#reader-view').hidden,{},id);
  await page.waitForSelector('#reader-title',{visible:true});
  await page.evaluate(()=>history.forward());
  await page.waitForFunction(()=>!location.hash&&!document.querySelector('#library-view').hidden);
  await page.setViewport({width:390,height:844});await click('.sb-bottom [data-action=reading]');
  await page.waitForSelector('#reader-title');assert.ok(page.url().endsWith('#'+id));
  await click('.sb-reader-actions [data-action=contents]');
  await click('#tools-dialog [data-chapter="1"]');
  assert.equal(await page.$eval('#chapter-heading',e=>e.textContent),selected.revision.chapters[1].title);
  await page.setViewport({width:1440,height:1000});await click('[data-chapter="0"]');
};
