module.exports=async({page,base,id,selected,click,shot,close,assert})=>{
  await page.goto(`${base}/?ui=v2#${id}`);await page.waitForSelector('#reader-title');
  assert.equal(await page.$eval('#reader-title',e=>e.textContent),selected.novel.title);
  await page.waitForFunction(()=>[...document.querySelectorAll('.story-image img')].every(e=>!e.hidden&&e.naturalWidth>0));
  assert.equal(await page.$$eval('.story-image img',e=>e.length),2);await shot('desktop-reader');
  const text=await page.$$eval('[data-text-block]',es=>es.map(e=>e.textContent));
  assert.deepEqual(text,selected.revision.chapters.flatMap(c=>c.scenes.flatMap(s=>s.blocks.map(b=>b.text))));
  await page.evaluate(()=>scrollTo(0,800));
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('sb2.recent'))[0].top>750);
  const before=await page.evaluate(()=>scrollY);
  await click('#back');await click('#hero [data-open]');
  await page.waitForFunction(y=>Math.abs(scrollY-y)<3,{},before);
  await page.reload();await page.waitForFunction(y=>Math.abs(scrollY-y)<3,{},before);
  await click('#aaBtn');await click('[data-pref=font][data-val=sans]');
  await page.$eval('#fs',e=>{e.value=22;e.dispatchEvent(new Event('input',{bubbles:true}));});
  assert.equal(await page.$eval('.story-block',e=>getComputedStyle(e).fontSize),'22px');
  await click('[data-pref=font][data-val=serif]');
  await page.$eval('#fs',e=>{e.value=18;e.dispatchEvent(new Event('input',{bubbles:true}));});await close();
  await click('[data-jump=chapter-2]');await page.waitForFunction(()=>document.querySelector('#rbar-chapter').textContent.includes('2/2'));
  await click('#back');await click('[data-lang-btn=zh]');await click('#hero [data-open]');
  await page.waitForSelector('#reader-title');assert.equal(await page.$eval('html',e=>e.lang),'zh-Hant');
  assert.deepEqual(await page.$$eval('[data-text-block]',es=>es.map(e=>e.textContent)),text);
  await click('#back');await click('[data-lang-btn=en]');await page.evaluate(()=>history.back());
  await page.waitForSelector('#reader-title',{visible:true});
};
